host-url: "http://localhost:8080"

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: "jdbc:postgresql://localhost:5431/Somedman"
    username: postgres
    password: Password
